version: 3

tasks:
  app:dev:
    cmds:
      - task: songs:process
      - task: config:generate
      - npm run dev
  app:build:
    cmd: |
      npm run build
  app:preview:
    cmd: |
      npm run preview
  app:deploy:
    cmds:
      - task: songs:process
      - task: config:generate
      - task: app:build
      - |
        echo "🚀 Deploying React app to S3..."
        # Get the S3 bucket name from Terraform outputs
        BUCKET_NAME=$(cd infra && terraform output -raw s3_bucket_name)
        if [ -z "$BUCKET_NAME" ]; then
          echo "❌ Error: Could not get S3 bucket name from Terraform outputs"
          echo "Make sure you've run 'task infra:apply' first"
          exit 1
        fi
        echo "📦 Deploying to bucket: $BUCKET_NAME"
        # Sync the built React app to S3
        aws s3 sync dist/ s3://$BUCKET_NAME --delete
        if [ $? -eq 0 ]; then
          echo "✅ Deployment successful!"
          echo "🌐 Your app is available at: $(cd infra && terraform output -raw website_url)"
        else
          echo "❌ Deployment failed"
          exit 1
        fi
  env:init:
    cmd: |
      set -a; source infra/.env; set +a
  infra:init:
    cmds:
      - task: env:init
      - |
        terraform init -reconfigure \
          -backend-config="bucket=$TF_STATE_BUCKET" \
          -backend-config="key=$TF_STATE_KEY" \
          -backend-config="region=$TF_STATE_REGION" \
          -backend-config="dynamodb_table=$TF_STATE_DYNAMODB_TABLE" \
          -backend-config="encrypt=true"
  infra:plan:
    cmd: |
      cd infra && terraform plan
  infra:apply:
    cmd: |
      cd infra && terraform apply
  infra:destroy:
    cmd: |
      cd infra && terraform destroy
  ssl:status:
    desc: "Check SSL certificate validation status"
    cmd: |
      cd infra && terraform output certificate_validation_status
  ssl:info:
    desc: "Display SSL certificate information"
    cmd: |
      echo "SSL Certificate Information:"
      echo "Domain: $(cd infra && terraform output -raw certificate_domain_name)"
      echo "ARN: $(cd infra && terraform output -raw certificate_arn)"
      echo "Status: $(cd infra && terraform output -raw certificate_validation_status)"
      echo ""
      echo "Website URLs:"
      echo "Custom Domain: $(cd infra && terraform output -raw website_url)"
      echo "CloudFront URL: $(cd infra && terraform output -raw cloudfront_url)"
  songs:process:
    desc: "Run the process_songs.py script with virtual environment setup"
    cmds:
      - |
        echo "🐍 Setting up Python virtual environment..."
        cd scripts
        if [ ! -d "venv" ]; then
          python -m venv venv
          echo "✅ Virtual environment created"
        else
          echo "✅ Virtual environment already exists"
        fi
        source venv/bin/activate
        echo "📦 Installing requirements..."
        pip install -r requirements.txt
        echo "🚀 Running process_songs.py..."
        python process_songs.py
  config:generate:
    desc: "Convert song_list.yaml to appConfig.json for the app"
    cmds:
      - |
        echo "🔄 Converting YAML to JSON..."
        cd scripts
        if [ ! -d "venv" ]; then
          python -m venv venv
        fi
        source venv/bin/activate
        pip install -r requirements.txt -q
        python generate_config.py
